-- Criação da tabela principal para o modelo 'Aluno'
CREATE TABLE "aluno" (
    "user_id" VARCHAR(150) NOT NULL PRIMARY KEY,
    "cpf" VARCHAR(14) NOT NULL UNIQUE,
    "data_nasc" DATE NOT NULL DEFAULT CURRENT_DATE,
    "turma_id" BIGINT NULL,
    
    CONSTRAINT "escola_aluno_user_id_fkey" 
        FOREIGN KEY ("user_id") 
        REFERENCES "auth_user" ("id")
        ON DELETE CASCADE,
        
    CONSTRAINT "escola_aluno_turma_id_fkey" 
        FOREIGN KEY ("turma_id") 
        REFERENCES "escola_turma" ("id")
        ON DELETE SET NULL
);

CREATE INDEX "escola_aluno_turma_id_idx" 
    ON "escola_aluno" ("turma_id");


-- Criação da tabela principal para o modelo 'Direcao'
CREATE TABLE "direcao" (
    "user_id" VARCHAR(150) NOT NULL PRIMARY KEY,
    "cpf" VARCHAR(14) NOT NULL UNIQUE,
    "data_nasc" DATE NOT NULL DEFAULT CURRENT_DATE,
    
    CONSTRAINT "escola_direcao_user_id_fkey" 
        FOREIGN KEY ("user_id") 
        REFERENCES "auth_user" ("id")
        ON DELETE CASCADE
);
-- Criação da tabela principal para o modelo 'Disciplina'
CREATE TABLE "disciplina" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    "nome_disciplina" VARCHAR(50) NOT NULL,
    "data_criacao" TIMESTAMP NOT NULL DEFAULT '1999-01-01 00:00:00'
);


-- Criação da tabela principal para o modelo 'Docente'
CREATE TABLE "docente" (
    "user_id" VARCHAR(150) NOT NULL PRIMARY KEY,
    "cpf" VARCHAR(14) NOT NULL UNIQUE,
    "data_nasc" DATE NOT NULL DEFAULT CURRENT_DATE,
    "turma_id" BIGINT NULL,
    "disciplina_id" BIGINT NULL,
    
    CONSTRAINT "escola_docente_user_id_fkey" 
        FOREIGN KEY ("user_id") 
        REFERENCES "auth_user" ("id") 
        ON DELETE CASCADE,
        
    CONSTRAINT "escola_docente_turma_id_fkey" 
        FOREIGN KEY ("turma_id") 
        REFERENCES "escola_turma" ("id") 
        ON DELETE SET NULL,
        
    CONSTRAINT "escola_docente_disciplina_id_fkey" 
        FOREIGN KEY ("disciplina_id") 
        REFERENCES "escola_disciplina" ("id") 
        ON DELETE SET NULL
);

CREATE INDEX "escola_docente_turma_id_idx" 
    ON "escola_docente" ("turma_id");
    
CREATE INDEX "escola_docente_disciplina_id_idx" 
    ON "escola_docente" ("disciplina_id");

-- Criação da tabela principal para o modelo 'Turma'
CREATE TABLE "turma" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    "nome_turma" VARCHAR(50) NOT NULL,
    "ano" VARCHAR(10) NOT NULL DEFAULT '1ª Ano',
    "data_criacao" TIMESTAMP NOT NULL DEFAULT '1999-01-01 00:00:00'
);